/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { JSX } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cylinder020: THREE.Mesh;
    Cylinder020_1: THREE.Mesh;
    Cylinder020_2: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder002_1: THREE.Mesh;
    Sphere005: THREE.Mesh;
    Sphere005_1: THREE.Mesh;
    Head003: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube003_2: THREE.Mesh;
  };
  materials: {
    Black: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
    Skin: THREE.MeshStandardMaterial;
  };
};

export function Object(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/3d/character.glb',
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020_1.geometry}
          material={materials.White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020_2.geometry}
          material={materials.Red}
        />
        <group position={[0.003, -0.14, 0.017]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={materials.Black}
          />
        </group>
        <group position={[0.003, 0.568, -0.017]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere005.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere005_1.geometry}
            material={materials.White}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Head003.geometry}
          material={materials.Skin}
          position={[0.003, 0.568, -0.017]}
        />
        <group position={[0.003, 0.686, -0.011]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials.Black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_1.geometry}
            material={materials.White}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube003_2.geometry}
            material={materials.Red}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/3d/character.glb');
